import { Course } from '../types';

export const defaultCourses: Course[] = [
  {
    id: 'course-beginner-comprehensive',
    slug: 'beginner-driving-mastery',
    title: 'Beginner Driving Mastery (Zero to Confident Driver)',
    shortTitle: 'Beginner Driving Mastery',
    badge: 'Most Popular',
    popular: true,
    category: 'beginner',
    transmission: 'both',
    level: 'Beginner',
    durationHours: 20,
    sessionsCount: 20,
    price: 6499,
    originalPrice: 7999,
    summary: 'Our signature zero-to-hero curriculum designed for total beginners. Includes cockpit orientation, clutch control, traffic maneuvers, automated RTO test track practice, and RTO documentation guidance.',
    description: 'Designed specifically for first-time learners who have never sat behind a steering wheel. We build your confidence step-by-step using dual-control safety vehicles, patient instructors, simulated track layouts, and real-world bumper-to-bumper traffic driving.',
    suitableFor: [
      'Absolute beginners with zero driving experience',
      'Learners seeking first-attempt success on automated RTO tracks',
      'Nervous drivers wanting a patient, step-by-step approach',
      'Those applying for their first Indian Permanent Driving Licence',
    ],
    whatIncluded: [
      '20 hours of 1-on-1 private dual-control practical training',
      'Exclusive automated RTO track maneuvers practice ("8", "H", Gradient & Parallel)',
      'Sarathi Parivahan LL & DL documentation assistance',
      'Doorstep pickup & drop within 8 km radius',
      'Comprehensive road signs handbook & mock theory test app access',
      'Vehicle provided on the day of the official RTO driving test',
    ],
    learningOutcomes: [
      'Master clutch-bite point without engine stalling',
      'Confidently execute 3-point turns, tight reverse parking, and parallel parking',
      'Seamlessly merge and navigate complex roundabouts and multi-lane city traffic',
      'Handle steep hill-starts without rolling backward using handbrake technique',
      'Pass the automated RTO camera-monitored driving test with zero penalty points',
    ],
    syllabus: [
      {
        sessionNumber: 1,
        title: 'Cockpit Drill & Fundamental Controls (DSSSM Routine)',
        durationMinutes: 60,
        objective: 'Master Doors, Seat, Steering, Seatbelt, Mirrors adjustment, and ABC (Accelerator, Brake, Clutch) pedal muscle memory.',
        topics: ['Seat & mirror positioning for maximum blind-spot visibility', 'Gear selector pattern & neutral check', 'Starting and smooth idling', 'Emergency dual-pedal override walkthrough'],
      },
      {
        sessionNumber: 2,
        title: 'Moving Off, Stopping & Smooth Clutch Control',
        durationMinutes: 60,
        objective: 'Achieve zero-stall smooth start in 1st gear and controlled braking without jerking.',
        topics: ['Finding the clutch bite point', 'Creep speed control', 'Progressive gentle braking', 'Steering pull-push technique (Shuffle steering)'],
      },
      {
        sessionNumber: 3,
        title: 'Gear Shifting Progression (1st to 3rd) & Spatial Judgment',
        durationMinutes: 60,
        objective: 'Synchronize revs and gear changes smoothly while maintaining road lane discipline.',
        topics: ['Upshifting & downshifting rhythm', 'Maintaining safe 3-second following distance', 'Left-side vehicle width judgment drill'],
      },
      {
        sessionNumber: 4,
        title: 'Low-Traffic Neighborhood & Turning Fundamentals',
        durationMinutes: 60,
        objective: 'Execute left and right 90-degree turns with proper mirror-signal-maneuver routine.',
        topics: ['MSM (Mirror, Signal, Maneuver) protocol', 'Approach speed and gear selection', 'Pedestrian & speed breaker etiquette'],
      },
      {
        sessionNumber: 5,
        title: 'Hill Hold & Slope Start Mastery (Anti-Rollback)',
        durationMinutes: 60,
        objective: 'Stop and restart on a 15-degree incline without rolling backward by more than 2 inches.',
        topics: ['Handbrake coordinated release', 'Friction point balancing with throttle', 'Stop-and-go flyover traffic simulation'],
        isRtoTrackSpecific: true,
      },
      {
        sessionNumber: 6,
        title: 'Automated RTO Track Track "8" & "S" Curve Navigation',
        durationMinutes: 60,
        objective: 'Navigate figure-8 track without touching side kerbs or camera sensor poles.',
        topics: ['Forward steering lock timing', 'Speed control without throttle surge', 'Sensor pole clearance cues'],
        isRtoTrackSpecific: true,
      },
      {
        sessionNumber: 7,
        title: 'Automated RTO Track "H" Maneuver & Tight Reversing',
        durationMinutes: 60,
        objective: 'Complete forward and reverse H-track box parking seamlessly.',
        topics: ['Side mirror reference points', 'Reverse steering orientation', 'Centering vehicle within the parking bay'],
        isRtoTrackSpecific: true,
      },
      {
        sessionNumber: 8,
        title: 'Perpendicular, Angular & Parallel Street Parking',
        durationMinutes: 60,
        objective: 'Park safely in tight shopping mall and roadside curbside spots in 2 moves.',
        topics: ['45-degree angle entry method', 'Bumper-to-mirror alignment cues', 'Hazard light signaling & curb distance'],
      },
      {
        sessionNumber: 9,
        title: 'Bumper-to-Bumper Heavy City Traffic & Flyovers',
        durationMinutes: 60,
        objective: 'Maintain composure and smooth spacing during peak rush-hour traffic.',
        topics: ['Managing two-wheeler cutting behavior', 'Frequent clutch modulation', 'Lane change assertiveness with blinkers'],
      },
      {
        sessionNumber: 10,
        title: 'RTO Mock Driving Test Simulation & Final Assessment',
        durationMinutes: 60,
        objective: 'Simulate complete RTO test under strict timer and camera grading conditions.',
        topics: ['Full simulated track test', 'Document verification checklist rehearsal', 'Instructor feedback & readiness sign-off'],
        isRtoTrackSpecific: true,
      },
    ],
    faqs: [
      {
        question: 'Do I need a Learner’s Licence before starting the course?',
        answer: 'You can begin training on our private closed track immediately. For public road sessions, we help you apply for your online Learner’s Licence (LL) within the first 2 days through the Parivahan Sarathi portal.',
      },
      {
        question: 'Can I choose between a Manual and an Automatic vehicle?',
        answer: 'Yes! We offer both manual (Swift, i10, Baleno) and automatic (CVT/AMT/AT) training cars. You can even split your package (12 hrs Manual + 8 hrs Automatic).',
      },
      {
        question: 'What happens if I make a mistake or stall the car during a lesson?',
        answer: 'All our training cars are equipped with approved dual-control pedals. Your certified instructor has full secondary clutch and brake controls, ensuring 100% safety at all times.',
      },
    ],
  },
  {
    id: 'course-automatic-specialist',
    slug: 'automatic-transmission-mastery',
    title: 'Automatic Transmission (AT/AMT/CVT) Specialist',
    shortTitle: 'Automatic Transmission Specialist',
    badge: 'Stress-Free',
    popular: false,
    category: 'automatic',
    transmission: 'automatic',
    level: 'Beginner',
    durationHours: 15,
    sessionsCount: 15,
    price: 5499,
    originalPrice: 6999,
    summary: 'Focus exclusively on modern automatic vehicles. Eliminate clutch fatigue and master two-pedal driving, creep control, hill-hold assist, and stress-free city commuting.',
    description: 'Automatic cars represent over 45% of new vehicle purchases in India. This course eliminates the steep learning curve of clutch bite-points and focuses immediately on steering precision, spatial judgment, overtaking safety, and intelligent gear mode selection (D, N, R, P, S, L).',
    suitableFor: [
      'City commuters wanting effortless daily driving without clutch fatigue',
      'Learners buying or driving an automatic hatchback, sedan, or EV',
      'Working professionals seeking quick, confident mastery in fewer sessions',
    ],
    whatIncluded: [
      '15 hours of private 1-on-1 automatic training in modern dual-control AT cars',
      'Creep-mode parking and hill descent techniques',
      'Emergency braking & ABS engagement drills',
      'Doorstep pickup & drop included',
      'RTO test preparation for Automatic vehicle endorsement',
    ],
    learningOutcomes: [
      'Right-foot-only discipline (preventing dangerous two-footed brake/gas confusion)',
      'Effortless stop-and-go in dense flyover traffic with hill-assist',
      'Precision crawling in tight parking basements without jerking',
      'Highway cruising, cruise-control operation, and kick-down overtaking',
    ],
    syllabus: [
      {
        sessionNumber: 1,
        title: 'Automatic Shifter Modes & Right-Foot Protocol',
        durationMinutes: 60,
        objective: 'Establish correct foot positioning (left foot planted on dead pedal) and shift gate familiarity.',
        topics: ['Park, Reverse, Neutral, Drive, Sport modes', 'Shift lock release and brake interlock', 'Single-foot pedal pivot technique'],
      },
      {
        sessionNumber: 2,
        title: 'Creep Speed Regulation & Smooth Braking',
        durationMinutes: 60,
        objective: 'Harness idle engine creep for seamless low-speed navigation.',
        topics: ['Modulating brake pressure for millimeter parking', 'Threshold braking from 40 km/h', 'Understanding crawl behavior on slopes'],
      },
      {
        sessionNumber: 3,
        title: 'City Traffic & Roundabout Management',
        durationMinutes: 60,
        objective: 'Handle active traffic junctions without hesitation.',
        topics: ['Quick gap recognition', 'Kickdown response latency management', 'Smooth deceleration at traffic lights'],
      },
      {
        sessionNumber: 4,
        title: 'Multi-Level Basement & Parallel Parking',
        durationMinutes: 60,
        objective: 'Confidently park in tight office/mall basement slots.',
        topics: ['Reverse camera & sensor reliance balance', 'Mirror checks before reversing', 'Tight pillar navigation'],
      },
      {
        sessionNumber: 5,
        title: 'Expressway Merging & Cruise Control Basics',
        durationMinutes: 60,
        objective: 'Merge at 60-80 km/h and maintain lane stability on high-speed ring roads.',
        topics: ['Ramp acceleration', 'Blind-spot mirror glances at speed', 'Safe following distances'],
      },
    ],
    faqs: [
      {
        question: 'Will my Indian driving licence be valid for manual cars if I learn in automatic?',
        answer: 'Under current Indian Motor Vehicle rules, a Light Motor Vehicle (LMV) driving licence covers non-transport passenger cars. However, if you plan to drive manual cars regularly, we recommend our Hybrid or Beginner Mastery course.',
      },
      {
        question: 'Are automatic training cars more expensive to learn in?',
        answer: 'Our pricing is fully transparent with no hidden fuel surcharges. Automatic cars require fewer total hours to achieve complete comfort because there is no clutch stalls to overcome.',
      },
    ],
  },
  {
    id: 'course-refresher-confidence',
    slug: 'refresher-confidence-booster',
    title: 'Refresher & Confidence Booster (License Holders)',
    shortTitle: 'Refresher Course',
    badge: 'Fast-Track',
    popular: false,
    category: 'refresher',
    transmission: 'both',
    level: 'Intermediate',
    durationHours: 10,
    sessionsCount: 10,
    price: 3999,
    originalPrice: 4999,
    summary: 'Have a licence but feel terrified of taking the car out alone? Overcome driving anxiety, relearn heavy traffic navigation, complex parking, and your daily office route with a patient mentor.',
    description: 'Thousands of drivers pass their driving test only to leave their cars parked at home for months or years. Our Refresher Program is tailored around your specific fears — whether it is basement parking, night glare, highway merging, or peak-hour bottlenecks.',
    suitableFor: [
      'Drivers who have a licence but haven’t driven in months or years',
      'Nervous drivers afraid of driving alone during rush hours',
      'Car owners who recently bought a new car and want orientation on their specific model',
      'Drivers transitioning from small hatchback to larger sedan or compact SUV',
    ],
    whatIncluded: [
      '10 hours customized training (can be split between our dual-control car and your personal vehicle)',
      'Your actual daily office/home commute route practice',
      'Tight home garage & parking slot customized drill',
      'Night driving & high-beam glare management module',
      'Emergency roadside assistance & tyre puncture orientation',
    ],
    learningOutcomes: [
      'Eliminate driving anxiety and regain total independent control',
      'Master your actual home-to-office route with confidence',
      'Park in your tight home or apartment stilt parking without fear of scratches',
      'Handle aggressive honking and tight city bottlenecks calmly',
    ],
    syllabus: [
      {
        sessionNumber: 1,
        title: 'Diagnostic Drive & Confidence Assessment',
        durationMinutes: 60,
        objective: 'Identify specific anxiety triggers, clutch habits, and steering accuracy.',
        topics: ['Calm mindset orientation', 'Vehicle dimensions recalibration', 'Low-pressure neighborhood drive'],
      },
      {
        sessionNumber: 2,
        title: 'Peak Hour Heavy Traffic & Flyovers',
        durationMinutes: 60,
        objective: 'Conquer stop-and-go rush hour and complex traffic intersections.',
        topics: ['Assertive yet courteous lane positioning', 'Managing auto-rickshaws and two-wheelers', 'Hill starts in heavy traffic'],
      },
      {
        sessionNumber: 3,
        title: 'Customized Office Route Navigation',
        durationMinutes: 60,
        objective: 'Practice your exact daily commute including U-turns, flyovers, and tricky junctions.',
        topics: ['Route landmarking', 'Pre-emptive lane selection', 'Toll plaza & entry gate approaches'],
      },
      {
        sessionNumber: 4,
        title: 'Personal Home Parking & Basement Drills',
        durationMinutes: 60,
        objective: 'Park repeatedly in your actual apartment parking spot.',
        topics: ['Tight pillar maneuvers', 'Multi-level spiral ramp ascent/descent', 'Reverse parking within narrow lines'],
      },
      {
        sessionNumber: 5,
        title: 'Transition to Your Personal Car (Solo Readiness)',
        durationMinutes: 60,
        objective: 'Conduct a fully independent solo drive with the instructor seated in observer mode.',
        topics: ['Dashboard features & climate controls', 'Final confidence sign-off', 'Emergency checklist'],
      },
    ],
    faqs: [
      {
        question: 'Can I take the refresher lessons in my own personal car?',
        answer: 'Yes! We typically conduct the first 2-3 sessions in our dual-control vehicle to assess your baseline, then smoothly transition to your personal car for real-world familiarization.',
      },
    ],
  },
  {
    id: 'course-highway-night-defensive',
    slug: 'highway-night-defensive-mastery',
    title: 'Highway, Night & Defensive Driving Masterclass',
    shortTitle: 'Highway & Defensive Driving',
    badge: 'Advanced Skills',
    popular: false,
    category: 'highway_defensive',
    transmission: 'both',
    level: 'Advanced',
    durationHours: 12,
    sessionsCount: 6,
    price: 4999,
    originalPrice: 6299,
    summary: 'Master high-speed expressways (80–100 km/h), high-beam night glare management, heavy monsoon driving, emergency skid recovery, and defensive hazard perception.',
    description: 'Indian highways require unique defensive habits — recognizing wrong-side drivers, unlit vehicles, stray cattle, and sudden braking hazards. This course takes you out of the city and equips you with long-distance road trip mastery.',
    suitableFor: [
      'Drivers planning interstate road trips or regular highway commutes',
      'Drivers wanting to feel safe driving at night and in heavy monsoon rain',
      'Experienced city drivers wanting advanced defensive hazard prediction',
    ],
    whatIncluded: [
      '12 hours including 2 dedicated 3-hour expressway training trips',
      'Night-time drive module (7:00 PM – 10:00 PM)',
      'Monsoon skid & hydroplaning prevention techniques',
      'Emergency roadside protocols (puncture, battery jump-start, hazard triangles)',
    ],
    learningOutcomes: [
      'Safe high-speed lane changing and overtaking at 80+ km/h',
      'Coping with high-beam glare without losing sight of road shoulders',
      'Hydroplaning awareness and wet-weather braking distance compensation',
      'Hazard scanning 10–15 seconds down the road rather than just the car ahead',
    ],
    syllabus: [
      {
        sessionNumber: 1,
        title: 'High-Speed Physics & Lane Discipline (Expressway Entry)',
        durationMinutes: 120,
        objective: 'Master acceleration lane merging, 4-second gap rule, and fast-lane overtaking etiquette.',
        topics: ['Toll plaza safety & FASTag approach', 'Aerodynamic buffeting near heavy trucks', 'Blind spot head-checks at speed'],
      },
      {
        sessionNumber: 2,
        title: 'Defensive Hazard Prediction & Wrong-Side Traffic Protocols',
        durationMinutes: 120,
        objective: 'Identify and neutralize potential crash scenarios before they develop.',
        topics: ['Scanning roadside tractor & animal movement', 'Brake pump signaling for tailgaters', 'Escape lane planning'],
      },
      {
        sessionNumber: 3,
        title: 'Night Driving, Headlight Glare & Peripheral Vision',
        durationMinutes: 120,
        objective: 'Drive safely in darkness and manage oncoming high-beams.',
        topics: ['Using road edge markings when blinded by glare', 'High vs Low beam courtesy', 'Unlit obstacle detection'],
      },
    ],
    faqs: [
      {
        question: 'Do we drive on actual National / State Highways?',
        answer: 'Yes, our highway sessions are conducted on approved major expressways and ring roads under active instructor supervision.',
      },
    ],
  },
  {
    id: 'course-rto-test-express',
    slug: 'rto-test-track-readiness',
    title: 'RTO Test-Track Readiness & Licence Endorsement',
    shortTitle: 'RTO Test Track Prep',
    badge: '100% Guaranteed Track Prep',
    popular: false,
    category: 'rto_prep',
    transmission: 'both',
    level: 'Intermediate',
    durationHours: 8,
    sessionsCount: 8,
    price: 3499,
    originalPrice: 4499,
    summary: 'Targeted drill specifically for passing the automated RTO camera-monitored driving test. Master the Figure "8", "H" Box, Parallel Bay, and Gradient Slope with zero sensor infractions.',
    description: 'Automated Driving Test Tracks (ADTT) use electronic sensors and high-speed overhead cameras where even a single touch on the yellow line or stalling on the incline causes an immediate fail. This targeted boot-camp guarantees you master every single sensor landmark.',
    suitableFor: [
      'Learners who have an upcoming RTO Driving Test date',
      'Candidates who failed a previous RTO test and need specific track correction',
      'Confident drivers who just need to understand the automated track camera layout',
    ],
    whatIncluded: [
      '8 dedicated hours on replica simulated automated test tracks',
      'Exact dimension practice of official RTO Figure-8, H-box, and Gradient Stop tracks',
      'Our school dual-control car provided on test day at the RTO',
      'Mock test scoring with digital time and error reports',
    ],
    learningOutcomes: [
      'Clear the Figure-8 within the official RTO time limit without wheel kerbing',
      'Flawless H-box reverse entry without stopping or extra steering adjustments',
      'Pass the gradient hill-start test with zero rollback',
      'Know all 15 mandatory hand signals and road signs asked in pre-drive evaluation',
    ],
    syllabus: [
      {
        sessionNumber: 1,
        title: 'Figure "8" Track Forward Steering Precision',
        durationMinutes: 60,
        objective: 'Maintain constant speed and tight turning radius inside the 8-track sensors.',
        topics: ['Steering entry angle', 'Throttle lock technique', 'Avoiding camera-trip line touches'],
        isRtoTrackSpecific: true,
      },
      {
        sessionNumber: 2,
        title: '"H" Track Forward & Reverse Box Parking',
        durationMinutes: 60,
        objective: 'Execute seamless forward entry, reverse bay positioning, and exit without stopping.',
        topics: ['Reference marker alignment with rear quarter window', 'One-turn reverse lock', 'Bay centering'],
        isRtoTrackSpecific: true,
      },
      {
        sessionNumber: 3,
        title: 'Gradient Slope Stop & Restart (Under 10-Second Rule)',
        durationMinutes: 60,
        objective: 'Stop between sensor lines on the slope and restart cleanly within 10 seconds.',
        topics: ['Clutch bite-hold without handbrake drop', 'Throttle blip technique', 'Zero rollback execution'],
        isRtoTrackSpecific: true,
      },
      {
        sessionNumber: 4,
        title: 'Full Mock RTO Examination & Scoring Audit',
        durationMinutes: 60,
        objective: 'Complete full test track simulation with timer and zero error tolerance.',
        topics: ['Official test dress code & paperwork review', 'Seatbelt & mirror inspection checklist', 'Final sign-off'],
        isRtoTrackSpecific: true,
      },
    ],
    faqs: [
      {
        question: 'Will DriveCraft provide the car for my RTO test?',
        answer: 'Yes! Our package includes our academy car and instructor escort at the RTO track on your scheduled test day.',
      },
    ],
  },
  {
    id: 'course-women-priority-coaching',
    slug: 'women-priority-driving-coaching',
    title: 'Women-Priority Driving Coaching (Empowerment Batch)',
    shortTitle: 'Women-Priority Coaching',
    badge: '100% Patient & Safe',
    popular: false,
    category: 'beginner',
    transmission: 'both',
    level: 'Beginner',
    durationHours: 20,
    sessionsCount: 20,
    price: 6999,
    originalPrice: 8499,
    summary: 'Dedicated female-instructed or senior certified patient mentors. Zero-rush, respectful, supportive learning environment with home doorstep pickup and SOS safety-equipped cars.',
    description: 'We believe learning to drive should be empowering, respectful, and completely pressure-free. Choose your preference of experienced female instructors or senior mentors who specialize in supportive, anxiety-free driving coaching.',
    suitableFor: [
      'Women seeking certified female instructors or patient mentors',
      'Homemakers, college students, and working women wanting independent mobility',
      'Learners who experienced harsh shouting or impatient teaching in traditional schools',
    ],
    whatIncluded: [
      '20 hours of 1-on-1 supportive driving coaching',
      'Dedicated female instructor option available upon request',
      'Doorstep pickup and drop from your home or workplace',
      'GPS-tracked vehicles with in-cabin safety protocols',
      'Child-seat orientation & family car dimensions coaching',
    ],
    learningOutcomes: [
      'Drive with total self-assurance and independence anywhere in the city',
      'Drop kids to school, navigate mall parking, and manage night commutes safely',
      'Confidently handle car breakdown checks, fuel station visits, and tyre pressure checks',
    ],
    syllabus: [
      {
        sessionNumber: 1,
        title: 'Supportive Foundation & Zero-Pressure Orientation',
        durationMinutes: 60,
        objective: 'Create a comfortable, supportive environment with familiar cockpit controls.',
        topics: ['Ergonomic seat adjustment for smaller/taller frames', 'Calm breathing and throttle sensitivity', 'Zero-rush neighborhood cruise'],
      },
      {
        sessionNumber: 2,
        title: 'Overcoming Traffic Apprehension & Steering Ease',
        durationMinutes: 60,
        objective: 'Build confidence with smooth steering and lane judgment.',
        topics: ['Light steering grip', 'Handling aggressive traffic assertively', 'Gentle progressive braking'],
      },
      {
        sessionNumber: 3,
        title: 'Daily Practical Realities: School Runs, Supermarkets & Malls',
        durationMinutes: 60,
        objective: 'Practice real-life everyday driving routines.',
        topics: ['Narrow residential lane maneuvering', 'Tight grocery market parking', 'Navigating speed breakers'],
      },
    ],
    faqs: [
      {
        question: 'Can I specifically request a female instructor?',
        answer: 'Yes! We have certified full-time female instructors on our roster. Simply select your preference during booking or contact us on WhatsApp.',
      },
    ],
  },
];
