import { Instructor } from '../types';

export const defaultInstructors: Instructor[] = [
  {
    id: 'inst-1',
    name: 'Rajesh Verma',
    role: 'Chief Safety Instructor & RTO Track Specialist',
    experienceYears: 14,
    rating: 4.98,
    studentCount: 3200,
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
    bio: 'Former defence driving coach with 14+ years of specialized motor training experience. Rajesh has guided over 3,000 learners to first-attempt automated RTO test passes with zero stress.',
    languages: ['Hindi', 'English', 'Punjabi'],
    specialties: ['Automated RTO Track "8" & "H" Drills', 'Clutch Bite Point Muscle Memory', 'Highway Night Driving'],
    transmissionSpecialty: 'both',
    verifiedBadges: ['MoRTH Certified Instructor', 'Defensive Driving Master', '14+ Yrs Experience'],
    quote: 'Driving is not about speed; it is about predicting what happens 10 seconds ahead on the road.',
  },
  {
    id: 'inst-2',
    name: 'Pooja Sharma',
    role: 'Senior Instructor & Women-Priority Coach',
    experienceYears: 9,
    rating: 4.96,
    studentCount: 1950,
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    bio: 'Pooja specializes in coaching first-time nervous learners, homemakers, and working professionals. Her ultra-calm, encouraging approach eliminates driving anxiety completely.',
    languages: ['Hindi', 'English'],
    specialties: ['Anxiety Reduction', 'Automatic Transmission', 'Tight Apartment & Mall Parking'],
    transmissionSpecialty: 'both',
    verifiedBadges: ['Certified Dual-Pedal Master', 'Anxiety Specialist', 'Top Rated 2024'],
    quote: 'Once you realize the dual-control car keeps you 100% safe, fear turns into pure confidence.',
  },
  {
    id: 'inst-3',
    name: 'Anand Sundaram',
    role: 'Technical Fleet Lead & Precision Maneuver Mentor',
    experienceYears: 11,
    rating: 4.94,
    studentCount: 2400,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    bio: 'Mechanical engineer turned certified driving trainer. Anand breaks down vehicle dynamics, clutch hydraulics, and steering geometry into intuitive everyday metaphors.',
    languages: ['English', 'Tamil', 'Kannada', 'Hindi'],
    specialties: ['Manual Transmission Mastery', 'Slope & Hill-Hold Starts', 'Traffic Merging Dynamics'],
    transmissionSpecialty: 'manual',
    verifiedBadges: ['Automotive Engineer', 'South Zone Top Instructor', '11+ Yrs Experience'],
    quote: 'Understand what the clutch is doing mechanically, and your feet will never make a mistake.',
  },
  {
    id: 'inst-4',
    name: 'Simran Kaur',
    role: 'City Traffic & Commute Route Specialist',
    experienceYears: 8,
    rating: 4.95,
    studentCount: 1600,
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    bio: 'Simran specializes in daily commute training, helping learners conquer complex city junctions, multi-tier flyovers, and narrow market routes with total composure.',
    languages: ['Hindi', 'English', 'Punjabi'],
    specialties: ['Rush-Hour Navigation', 'Flyover Traffic', 'Mirror & Blind-Spot Discipline'],
    transmissionSpecialty: 'automatic',
    verifiedBadges: ['Urban Mobility Specialist', 'Patient Mentor', 'Certified First Responder'],
    quote: 'Confidence is built one junction at a time. We celebrate every smooth turn and clean stop.',
  },
  {
    id: 'inst-5',
    name: 'Vikramaditya Shinde',
    role: 'Defensive Driving & Expressway Master',
    experienceYears: 12,
    rating: 4.92,
    studentCount: 2800,
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    bio: 'Experienced highway coach and emergency vehicle driver. Vikram trains students in high-speed hazard perception, monsoon driving safety, and sudden obstacle avoidance.',
    languages: ['Marathi', 'Hindi', 'English'],
    specialties: ['Expressway Merging (80+ km/h)', 'Monsoon Skid Prevention', 'Emergency Braking & ABS'],
    transmissionSpecialty: 'both',
    verifiedBadges: ['Advanced Road Safety Certified', 'Monsoon Driving Specialist'],
    quote: 'On Indian highways, defensive driving is not optional — it is your superpower.',
  },
  {
    id: 'inst-6',
    name: 'Meenakshi Iyer',
    role: 'Refresher Program & Senior Driver Coach',
    experienceYears: 10,
    rating: 4.97,
    studentCount: 1850,
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    bio: 'Meenakshi has a gifted touch for learners who haven\'t driven in 5 to 10 years after getting their licence. She builds up courage through gentle, structured daily neighborhood drives.',
    languages: ['English', 'Tamil', 'Hindi'],
    specialties: ['Post-Licence Anxiety', 'Personal Car Orientation', 'Reverse Camera & Sensor Cues'],
    transmissionSpecialty: 'both',
    verifiedBadges: ['Refresher Specialist', 'Zero-Anxiety Coach', '10+ Yrs Experience'],
    quote: 'It doesn’t matter how long your car has been parked. In just five sessions, you will reclaim the road.',
  },
  {
    id: 'inst-7',
    name: 'Kabir Malhotra',
    role: 'Automatic & EV Dual-Control Specialist',
    experienceYears: 7,
    rating: 4.96,
    studentCount: 1420,
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    bio: 'Specialist in modern EV and AMT automatic vehicles. Kabir coaches learners on regenerative braking, battery range management, and smooth creep-speed parking control.',
    languages: ['Hindi', 'English'],
    specialties: ['Electric Vehicle (EV) Dynamics', 'AMT & CVT Automatics', 'Pedestrian Hazard Awareness'],
    transmissionSpecialty: 'automatic',
    verifiedBadges: ['EV Training Certified', 'Smooth Drive Specialist'],
    quote: 'Modern cars are effortless when you master steering calibration and throttle gentleness.',
  },
  {
    id: 'inst-8',
    name: 'Sunita Patil',
    role: 'Night Driving & Parallel Parking Coach',
    experienceYears: 9,
    rating: 4.95,
    studentCount: 1750,
    photoUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=600&q=80',
    bio: 'Sunita takes the intimidation out of parallel parking between tight SUVs and low-visibility evening driving with systematic reference-point formulas.',
    languages: ['Hindi', 'Marathi', 'English'],
    specialties: ['Parallel & Perpendicular Bay Parking', 'Night Headlight Glare Management', 'Rain Driving Safety'],
    transmissionSpecialty: 'both',
    verifiedBadges: ['Precision Parking Master', 'Patient Female Coach'],
    quote: 'Parking is simply geometry with clear visual reference markers. Anyone can master it.',
  },
  {
    id: 'inst-9',
    name: 'Arjun Nambiar',
    role: 'RTO Test Simulator & Hill-Hold Expert',
    experienceYears: 13,
    rating: 4.99,
    studentCount: 3100,
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    bio: 'Former RTO simulator evaluator with an unmatched 99% track pass record. Arjun demystifies overhead camera sensors and timer checkpoints on automated test tracks.',
    languages: ['English', 'Malayalam', 'Hindi', 'Tamil'],
    specialties: ['ADTT Figure-8 Speed Regulation', 'Handbrake Hill-Hold Starts', 'Clutch Zero-Rollback'],
    transmissionSpecialty: 'both',
    verifiedBadges: ['Track Simulator Expert', 'MoRTH Master Trainer', '13+ Yrs Coaching'],
    quote: 'Master the handbrake bite point and no hill in the world will ever intimidate you.',
  },
];
