import { PricingPackage, PricingAddOn } from '../types';

export const defaultPricingPackages: PricingPackage[] = [
  {
    id: 'pkg-starter',
    name: 'Starter Confidence',
    slug: 'starter-confidence',
    tagline: 'Ideal for learners with basic familiarity or those needing a targeted refresher.',
    price: 3999,
    originalPrice: 4999,
    durationHours: 10,
    sessionsCount: 10,
    popular: false,
    idealFor: 'Refresher drivers, drivers with a licence wanting city practice, or dual-control familiarization.',
    featuresIncluded: [
      '10 Hours of 1-on-1 private dual-control driving lessons',
      'Doorstep pickup & drop (within 6 km radius)',
      'Cockpit setup & mirror calibration mastery',
      'Heavy city traffic & roundabout navigation',
      'Parallel & reverse parking fundamentals',
      'Complimentary Digital Highway Safety Guidebook',
    ],
    featuresExcluded: [
      'RTO Test Car Escort on exam day',
      'Sarathi Portal LL & DL document filing assistance',
      'Simulated Automated Track "8" & "H" sensor sessions',
    ],
    vehicleTypesIncluded: ['Hatchback Manual or Automatic (Swift / i10 / Baleno)'],
    emiAvailable: false,
  },
  {
    id: 'pkg-standard',
    name: 'Standard Licence Mastery',
    slug: 'standard-licence-mastery',
    tagline: 'Our complete end-to-end zero-to-licence package for first-time learners.',
    price: 6499,
    originalPrice: 7999,
    durationHours: 20,
    sessionsCount: 20,
    popular: true,
    badge: 'Most Popular',
    idealFor: 'Complete beginners aiming for 100% first-attempt pass on automated RTO tracks.',
    featuresIncluded: [
      '20 Hours of 1-on-1 private dual-control driving lessons',
      'Doorstep pickup & drop (within 10 km radius)',
      'Complete Automated RTO Track replica training ("8", "H", Slope & Box)',
      'Parivahan Sarathi LL & DL application & slot booking support',
      'DriveCraft car & certified instructor provided on RTO test day',
      'Hill-hold start and zero-rollback slope mastery',
      'Night-time city driving session included',
      'Unlimited mock theory tests on student portal',
    ],
    featuresExcluded: [
      'Expressway high-speed long road trip module',
    ],
    vehicleTypesIncluded: ['Choice of Manual or Automatic Hatchback / Compact Sedan'],
    emiAvailable: true,
  },
  {
    id: 'pkg-mastery-pro',
    name: 'Mastery Pro & Highway Elite',
    slug: 'mastery-pro-highway',
    tagline: 'The ultimate all-inclusive driving package from beginner basics to expressway road trips.',
    price: 9499,
    originalPrice: 11999,
    durationHours: 30,
    sessionsCount: 25,
    popular: false,
    badge: 'All-Inclusive Elite',
    idealFor: 'Learners who want absolute mastery: city, automated RTO track, high-speed highways, and personal car transition.',
    featuresIncluded: [
      '30 Total Hours of comprehensive driving training',
      '20 Hours Dual-Control Training + 10 Hours Advanced Expressway & Personal Car coaching',
      'Dedicated 3-hour weekend expressway road trip module (80–100 km/h)',
      'Personal car orientation at your home (we coach you inside your own car)',
      'VIP RTO test escort with priority test car setup',
      'All government portal application and documentation assistance',
      'Night-time high-beam glare management and heavy rain driving',
      'Basement & tight apartment stilt parking specialized drill',
      'Emergency roadside assistance & tyre puncture replacement practical',
    ],
    featuresExcluded: [],
    vehicleTypesIncluded: ['Hatchback, Sedan, Compact SUV (Manual & Automatic)'],
    emiAvailable: true,
  },
  {
    id: 'pkg-hourly-custom',
    name: 'Hourly Custom Practice',
    slug: 'hourly-custom-practice',
    tagline: 'Flexible pay-as-you-go sessions for specific maneuver fixes or route practice.',
    price: 499,
    durationHours: 1,
    sessionsCount: 1,
    popular: false,
    badge: 'Flexible Pay-As-You-Go',
    idealFor: 'Drivers needing 1 or 2 targeted hours for a specific office route, parking slot, or test track practice.',
    featuresIncluded: [
      '1-on-1 private dual-control coaching by the hour',
      'Focus 100% on what you choose (e.g. only parallel parking, or only slope starts)',
      'Flexible slot booking via WhatsApp',
      'Available in both Manual and Automatic cars',
    ],
    featuresExcluded: [
      'Doorstep pickup (Hub pickup/drop)',
      'RTO test vehicle escort',
    ],
    vehicleTypesIncluded: ['Manual or Automatic'],
    emiAvailable: false,
  },
];

export const defaultPricingAddOns: PricingAddOn[] = [
  {
    id: 'addon-rto-car-escort',
    title: 'RTO Test Day Vehicle & Instructor Escort',
    description: 'We provide our dual-control training car, fuel, and an instructor at the RTO test track on your test day.',
    price: 999,
    perUnit: 'per test day',
    badge: 'Essential for External Applicants',
  },
  {
    id: 'addon-personal-car-transition',
    title: 'Personal Car Home Transition (2 Hours)',
    description: 'Our senior instructor visits your home and coaches you inside your own personal new car for familiarization.',
    price: 899,
    perUnit: '2-hour home session',
    badge: 'Popular for New Car Owners',
  },
  {
    id: 'addon-night-driving',
    title: 'Night & Rain Driving Master Module (2 Hours)',
    description: 'Specialized 8:00 PM – 10:00 PM coaching focusing on high-beam glare, peripheral vision, and wet asphalt braking.',
    price: 999,
    perUnit: '2-hour night session',
  },
  {
    id: 'addon-expressway-roadtrip',
    title: 'Expressway Highway Merging Module (3 Hours)',
    description: 'Continuous high-speed 60 km drive on the National Highway with FASTag toll crossing and overtaking rules.',
    price: 1499,
    perUnit: '3-hour highway trip',
  },
];

export const defaultComparisonCategories = [
  {
    category: 'Core Practical Driving Hours',
    features: [
      { name: '1-on-1 Dual-Control Practical Hours', starter: '10 Hours', standard: '20 Hours', mastery: '30 Hours' },
      { name: 'Doorstep Pickup & Drop', starter: 'Within 6 km', standard: 'Within 10 km', mastery: 'Within 15 km' },
      { name: 'Manual or Automatic Car Option', starter: true, standard: true, mastery: true },
      { name: 'Certified Verified Patient Instructor', starter: true, standard: true, mastery: true },
    ],
  },
  {
    category: 'RTO Track & Test Preparation',
    features: [
      { name: 'Automated RTO Track ("8" & "H") Drills', starter: false, standard: true, mastery: true },
      { name: 'Slope & Hill-Hold Anti-Rollback Drill', starter: 'Basic', standard: 'Comprehensive', mastery: 'Advanced' },
      { name: 'DriveCraft Car Provided on RTO Test Day', starter: 'Optional (₹999)', standard: true, mastery: 'VIP Priority' },
      { name: 'Sarathi Parivahan Document Filing Support', starter: false, standard: true, mastery: true },
    ],
  },
  {
    category: 'Advanced Real-World Driving',
    features: [
      { name: 'Heavy Traffic & Flyover Navigation', starter: true, standard: true, mastery: true },
      { name: 'Multi-Level Basement & Parallel Parking', starter: 'Basic', standard: true, mastery: 'Advanced' },
      { name: 'Night Driving & Glare Mitigation', starter: false, standard: '1 Session', mastery: 'Dedicated Module' },
      { name: 'High-Speed National Expressway Trip', starter: false, standard: false, mastery: '3 Hours Included' },
      { name: 'Personal Car Familiarization at Home', starter: false, standard: false, mastery: 'Included' },
    ],
  },
];
