import { RoadmapStep } from '../types';

export const defaultRoadmap: RoadmapStep[] = [
  {
    id: 'step-1-application',
    stepNumber: 1,
    title: "Learner's Licence (LL) Application & Aadhaar eKYC",
    subtitle: "Initiate official application via Parivahan Sarathi portal",
    stageName: 'Stage 1: Documentation & Registration',
    approxDuration: '1–2 Days',
    rtoPortalUrl: 'https://sarathi.parivahan.gov.in',
    summary: 'Submit Form 2 on the official Ministry of Road Transport and Highways (MoRTH) Parivahan portal using Aadhaar authentication. Upload required age and address proofs or complete contactless verification.',
    details: 'The Indian driving licence process begins with obtaining a Learner\'s Licence (LL). In most Indian states (including Delhi, Karnataka, Maharashtra, Uttar Pradesh, Tamil Nadu, etc.), Aadhaar-based e-KYC enables you to submit your application and take the online learner test completely from home without visiting an RTO office.',
    requiredDocuments: [
      'Aadhaar Card (Linked with active mobile number for OTP authentication)',
      'Age Proof (10th Standard Marksheet, Passport, Birth Certificate, or PAN Card)',
      'Address Proof (Aadhaar, Electricity Bill, Rental Agreement with Police Verification, or Voter ID)',
      'Form 1 (Self-declaration of physical fitness) or Form 1A (Medical Certificate for applicants over 40 years)',
      'Passport size digital photograph and digital signature',
    ],
    keyRulesToRemember: [
      'Minimum age requirement is 18 years for Light Motor Vehicle (LMV) passenger cars (16 years for gearless two-wheelers up to 50cc).',
      'Ensure the name and date of birth match exactly across your Aadhaar card and supporting educational documents to avoid portal rejection.',
      'Select the correct vehicle category: LMV (Light Motor Vehicle — Car/Jeep) or LMV-NT (Non-Transport).',
    ],
    instructorProTip: 'Always verify that your mobile number linked to Aadhaar is active, as both the Sarathi login OTP and test link credentials will be sent directly to that number.',
    checklistItems: [
      { id: 'c1-1', task: 'Visit sarathi.parivahan.gov.in and select your state', officialRequirement: true },
      { id: 'c1-2', task: 'Choose "Apply for Learner Licence" and authenticate via Aadhaar OTP', officialRequirement: true },
      { id: 'c1-3', task: 'Upload documents and sign the Form 1 health declaration', officialRequirement: true },
      { id: 'c1-4', task: 'Pay the official government application fee online', officialRequirement: true },
    ],
  },
  {
    id: 'step-2-ll-test',
    stepNumber: 2,
    title: "LL Computerized Theory & Road Sign Examination",
    subtitle: "Pass the 15-question traffic rules & sign test",
    stageName: 'Stage 2: Theory & Regulations',
    approxDuration: '1 Day (Valid for 6 Months)',
    rtoPortalUrl: 'https://sarathi.parivahan.gov.in',
    summary: 'Complete the mandatory computer-based or online proctored test on traffic signs, road rules, driver etiquette, and Motor Vehicle Act penalties. Scoring 9/15 or 12/20 (state dependent) immediately issues your digital Learner’s Licence.',
    details: 'The computerized LL test consists of multiple-choice questions covering mandatory, cautionary, and informatory road signs, right-of-way protocols, pedestrian crossings, speed limits, and alcohol/seatbelt regulations. Once passed, your Learner’s Licence is immediately generated as a downloadable PDF with a QR code and is valid for 6 months across all states in India.',
    requiredDocuments: [
      'Application Number & Password (sent via SMS from MoRTH)',
      'Webcam/Front camera enabled device (for contactless online test) or Appointment Slip (for RTO test center)',
    ],
    keyRulesToRemember: [
      'Learner’s Licence is valid for exactly 180 days (6 months) from the date of issuance.',
      'While driving with an LL on public roads, you MUST have a red "L" board (18 cm x 18 cm with 5 cm stroke) displayed on the front and rear of the vehicle.',
      'A permanent DL holder must accompany you in the front passenger seat at all times during public road practice.',
    ],
    instructorProTip: 'Pay special attention to rectangular blue signs (Informatory), circular red border signs (Mandatory / Prohibitory), and triangular signs (Cautionary). Our mobile study app includes all 200+ official Parivahan mock questions.',
    checklistItems: [
      { id: 'c2-1', task: 'Watch the mandatory MoRTH road safety tutorial video on the portal', officialRequirement: true },
      { id: 'c2-2', task: 'Attempt mock tests on the Parivahan portal or DriveCraft student portal', officialRequirement: false },
      { id: 'c2-3', task: 'Complete the online LL test with facial recognition or appear at RTO', officialRequirement: true },
      { id: 'c2-4', task: 'Download and print the official Form 3 Learner’s Licence PDF', officialRequirement: true },
    ],
  },
  {
    id: 'step-3-practical-training',
    stepNumber: 3,
    title: "Dual-Control Practical Training & Skill Building",
    subtitle: "Hands-on driving lessons with certified mentors",
    stageName: 'Stage 3: Behind-the-Wheel Mastery',
    approxDuration: '15–20 Days',
    summary: 'Begin your structured behind-the-wheel coaching in certified dual-control safety vehicles. Progress systematically from basic cockpit controls, steering, and clutch balance to complex city traffic, flyovers, and night driving.',
    details: 'This is where real-world confidence is forged. DriveCraft instructors follow our proprietary 4-Pillar Training System: Mechanical Familiarity, Spatial Judgment, Defensive Awareness, and Automated Track Maneuvers. With secondary dual-brake and clutch pedals on the instructor’s side, you learn safely with zero fear of accidents.',
    requiredDocuments: [
      'Original or Digital Copy of valid Form 3 Learner’s Licence',
      'DriveCraft Student Training Logbook',
    ],
    keyRulesToRemember: [
      'Always carry a digital copy of your LL in DigiLocker or mParivahan app during all driving sessions.',
      'Maintain the mandatory 3-second following distance rule in city traffic and 4 seconds on high-speed flyovers.',
      'Never practice on public expressways without dual-control instructor supervision during your learner phase.',
    ],
    instructorProTip: 'Do not stare at the gear lever or pedals while driving. Keep your eyes raised toward the horizon and scan 10 seconds ahead — muscle memory will guide your hands and feet naturally.',
    isSimulatorPhase: true,
    checklistItems: [
      { id: 'c3-1', task: 'Master the DSSSM cockpit setup routine', officialRequirement: false },
      { id: 'c3-2', task: 'Achieve consistent clutch bite-point control without engine stalling', officialRequirement: false },
      { id: 'c3-3', task: 'Complete 10+ hours of multi-lane city traffic navigation', officialRequirement: false },
      { id: 'c3-4', task: 'Practice night driving and high-beam glare mitigation', officialRequirement: false },
    ],
  },
  {
    id: 'step-4-practice-period',
    stepNumber: 4,
    title: "Mandatory 30-Day Maturation & Parking Drills",
    subtitle: "Legally required 30-day gap & precision parking drills",
    stageName: 'Stage 4: Mandatory Legal Maturation',
    approxDuration: 'Minimum 30 Days (Legal Requirement)',
    summary: 'Under Section 8 of the Indian Motor Vehicles Act, an applicant must hold an active Learner’s Licence for at least 30 continuous days before becoming eligible to apply for the Permanent Driving Licence skill test.',
    details: 'Use this mandatory 30-day practice window to cement your technical parking skills and fine-tune tricky maneuvers. At DriveCraft, we dedicate this phase to perfecting parallel parking, 90-degree angular garage parking, tight U-turns, and uphill slope starts on our private training tracks.',
    requiredDocuments: [
      'Active Learner’s Licence showing at least 30 elapsed days from date of issue',
      'Form 5 / Form 5B Driving School Training Certificate (issued by DriveCraft Academy upon course completion)',
    ],
    keyRulesToRemember: [
      'You CANNOT book your Permanent Driving Licence test appointment before the 30-day minimum period is complete.',
      'Your LL is valid for 180 days, giving you a 150-day window after the 30-day mark to schedule your permanent test.',
    ],
    instructorProTip: 'Master parking by using your vehicle’s side rear-quarter windows and side mirrors as geometric markers. Aligning the rear bumper with the adjacent car’s rear door handle guarantees a perfect 45-degree reverse entry.',
    checklistItems: [
      { id: 'c4-1', task: 'Verify 30 days have elapsed since Learner’s Licence issue date', officialRequirement: true },
      { id: 'c4-2', task: 'Complete parallel and reverse parking master drills', officialRequirement: false },
      { id: 'c4-3', task: 'Obtain Form 5 Certificate of Driving Competence from DriveCraft', officialRequirement: true },
      { id: 'c4-4', task: 'Log in to Parivahan portal to book the Permanent DL Test Slot', officialRequirement: true },
    ],
  },
  {
    id: 'step-5-rto-test',
    stepNumber: 5,
    title: "Automated Driving Test Track (ADTT) & Road Exam",
    subtitle: "Clear the sensor-monitored camera test tracks",
    stageName: 'Stage 5: Official Competency Exam',
    approxDuration: 'Half Day at RTO',
    rtoPortalUrl: 'https://sarathi.parivahan.gov.in',
    summary: 'Demonstrate your driving competence on the automated sensor-equipped RTO track. Successfully clear the Figure-8 track, H-Parking box, Gradient slope test, and real-road traffic assessment under Motor Vehicle Inspector (MVI) supervision.',
    details: 'Modern Automated Driving Test Tracks (ADTT) in Indian cities use overhead optical sensors and electronic pressure mats. The test evaluates: 1) Figure "8" without touching sensor poles, 2) Forward & Reverse "H" box parking without halting midway, 3) Parallel parking within the marked bay, and 4) Gradient slope stop-and-go with zero rollback. DriveCraft provides the training car and instructor escort on your test day.',
    requiredDocuments: [
      'Original Form 3 Learner’s Licence',
      'Printed DL Slot Booking Appointment Slip',
      'Valid Original Photo ID (Aadhaar Card / Passport)',
      'Vehicle Registration Certificate (RC), Valid Insurance, and Pollution Under Control (PUC) Certificate of test vehicle (provided by DriveCraft)',
      'Form 5 / 5B Training Certificate from accredited driving school',
    ],
    rtoTrackManeuvers: [
      'Figure "8" Track: Continuous forward steering without crossing border kerbs',
      '"H" Track: Forward entry, precision 90-degree reverse bay parking, and forward exit',
      'Gradient Track (Slope Test): Stop vehicle on 15% incline for 5 seconds and restart without rolling back > 2 inches',
      'Parallel Parking Bay: Reverse into single-space slot in max 2 steering attempts',
    ],
    keyRulesToRemember: [
      'Wear your seatbelt before even inserting the key / pressing ignition.',
      'Adjust all 3 rearview mirrors conspicuously so the camera and inspector note your inspection routine.',
      'Use indicator turn signals for EVERY turn, lane change, and parking entry on the track.',
      'If you touch any sensor pole or line, the computerized system assigns penalty points automatically.',
    ],
    instructorProTip: 'Keep your speed low and steady (10–15 km/h on the track). The automated test checks precision and control, not speed. Smooth clutch modulation and deliberate steering ensure a 100% first-attempt score.',
    checklistItems: [
      { id: 'c5-1', task: 'Arrive at RTO test track 30 minutes prior to slot time', officialRequirement: true },
      { id: 'c5-2', task: 'Complete document verification and biometrics at RTO counter', officialRequirement: true },
      { id: 'c5-3', task: 'Conduct vehicle pre-inspection with instructor', officialRequirement: false },
      { id: 'c5-4', task: 'Complete ADTT sensor track test and obtain passing slip', officialRequirement: true },
    ],
  },
  {
    id: 'step-6-licence-delivery',
    stepNumber: 6,
    title: "Smart Card DL Issuance & Lifelong Driving Freedom",
    subtitle: "Receive your Smart Card & digital licence on DigiLocker",
    stageName: 'Stage 6: Certified Independent Driver',
    approxDuration: '3–10 Days Delivery by Speed Post',
    rtoPortalUrl: 'https://digilocker.gov.in',
    summary: 'Upon passing the driving test, your official Smart Card Driving Licence is approved, printed, and dispatched to your registered address via India Post Speed Post. Instant digital access is unlocked on DigiLocker and mParivahan.',
    details: 'Congratulations! You are now a fully licensed, legally certified driver in India. Your Smart Card Driving Licence is valid for 20 years (or until age 40, whichever comes first). The digital copy stored in DigiLocker or mParivahan has 100% legal validity equivalent to the physical card under Rule 9A of the Central Motor Vehicles Rules.',
    requiredDocuments: [
      'Speed Post tracking number (received via SMS from RTO after dispatch)',
      'DigiLocker account linked with your Aadhaar and Driving Licence Number',
    ],
    keyRulesToRemember: [
      'Private LMV Driving Licences are valid for 20 years from issue date or until you turn 40 years old.',
      'Renewals after age 40 are valid for 10-year / 5-year periods with mandatory medical fitness certification (Form 1A).',
      'Never drink and drive — India maintains a strict BAC threshold with heavy fines and licence suspension under Section 185 of MV Act.',
    ],
    instructorProTip: 'Add your Driving Licence to your DigiLocker and mParivahan smartphone apps immediately. You will never need to carry the physical plastic card for routine traffic police checks.',
    checklistItems: [
      { id: 'c6-1', task: 'Track Speed Post dispatch status on India Post portal', officialRequirement: false },
      { id: 'c6-2', task: 'Fetch digital DL into DigiLocker and mParivahan apps', officialRequirement: true },
      { id: 'c6-3', task: 'Receive physical microchip Smart Card DL at your doorstep', officialRequirement: true },
      { id: 'c6-4', task: 'Enjoy lifelong safe, confident, and joyful driving with DriveCraft', officialRequirement: false },
    ],
  },
];
