import { SiteConfig } from '../types';

export const defaultSiteConfig: SiteConfig = {
  brandName: 'DriveCraft Motor Academy',
  tagline: 'Master Every Mile with Confidence & Safety',
  shortDescription: "India's premier certified driving academy providing 100% dual-control safety cars, patient certified instructors, automated RTO test-track preparation, and personalized doorstep lessons.",
  phoneDisplay: '+91 98765 43210',
  phoneDial: '+919876543210',
  whatsappNumber: '919876543210',
  whatsappDefaultMessage: 'Hello DriveCraft Academy! I would like to enquire about your driving courses and book a trial lesson.',
  email: 'admissions@drivecraft.in',
  emergencyHelpline: '1800-200-SAFE',
  foundedYear: '2016',
  hero: {
    badgeText: '100% Dual-Control Safety Fleet • Doorstep Pickup',
    headlineMain: 'Master Every Mile with ',
    headlineHighlight: 'Confidence',
    headlineEnd: ' & Total Safety.',
    subtitle: 'Learn driving in modern dual-control cars with patient certified mentors, replica automated RTO track training, and zero hidden fees.',
    bookingButtonText: 'Book a Driving Lesson',
    whatsappButtonText: 'WhatsApp Us',
    heroImageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=800&q=80',
    trustChecks: ['98.4% First-Attempt RTO Pass', 'Female & Male Mentors', 'Manual & Auto'],
  },
  coreValues: [
    {
      id: 'val-1',
      title: '100% Dual-Control Safety Fleet',
      description: 'Every training vehicle is equipped with secondary dual pedals. Your instructor stops the vehicle instantly if any hazard arises.',
      icon: 'ShieldCheck',
    },
    {
      id: 'val-2',
      title: 'Automated RTO Track Readiness',
      description: 'Drills on replica Figure-8, H-box parking, and slope hill-hold tracks ensure high first-attempt pass rates on camera-monitored exams.',
      icon: 'Award',
    },
    {
      id: 'val-3',
      title: 'Doorstep Pickup & Calm Coaching',
      description: 'Daily 1-hour slots scheduled directly from your home or office with background-verified, patient male & female mentors.',
      icon: 'Compass',
    },
  ],
  teamMembers: [
    {
      id: '1',
      name: 'Chadrack',
      role: 'director of photography',
      image: 'https://media.licdn.com/dms/image/v2/D4D03AQFnmLdpZW78yA/profile-displayphoto-scale_200_200/B4DZvM8NB2JMAY-/0/1768669895649?e=2147483647&v=beta&t=5VGAB-2gYupLNaHvJHECollR25THd-3oR5wngGlQiY4',
      social: { twitter: '#', linkedin: '#', behance: '#' },
    },
    {
      id: '2',
      name: 'Mak VieSAinte',
      role: 'FOUNDER',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2vnSxNNVGZV2MXRjlGELl-NgLl5kXdpDR6A&s',
      social: { twitter: '#', linkedin: '#' },
    },
    {
      id: '3',
      name: 'Osiris Balonga',
      role: 'LEAD FRONT-END',
      image: 'https://media.licdn.com/dms/image/v2/D4D03AQGVqrPPAGHtoQ/profile-displayphoto-scale_200_200/B4DZwhAkjaHwAY-/0/1770080338529?e=2147483647&v=beta&t=q-_6p1VCJ8NN8eHj9zUFwJZds_XpKez9Hy14SAIDp4M',
      social: { twitter: '#', linkedin: '#' },
    },
    {
      id: '4',
      name: 'Jacques',
      role: 'PRODUCT OWNER',
      image: 'https://media.licdn.com/dms/image/v2/D4D03AQE-Z7-S1LSYNQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1724143166545?e=2147483647&v=beta&t=6IPCwgOzblGt4p2fEdnY74gMbLyRHii5Ite3A39qQsY',
      social: { linkedin: '#' },
    },
    {
      id: '5',
      name: 'Riche Makso',
      role: 'CTO - PRODUCT DESIGNER',
      image: 'https://media.licdn.com/dms/image/v2/D4D03AQEkTAbZLlSrLg/profile-displayphoto-scale_200_200/B4DZoHdu8BGgAY-/0/1761061833315?e=2147483647&v=beta&t=Rg1dBTvq9X2heyhuhBwG2DsEkG65v0vQ35hF2FSeYns',
      social: { twitter: '#', linkedin: '#' },
    },
    {
      id: '6',
      name: 'Jemima',
      role: 'MAKE-UP ARTISTE',
      image: 'https://i.pravatar.cc/400?img=16',
      social: { instagram: '#' },
    },
  ],
  operatingHours: {
    weekdays: '6:00 AM – 8:00 PM (Lessons every hour)',
    weekends: '6:30 AM – 7:30 PM (Special weekend batches)',
    note: 'Office support available 8:00 AM – 9:00 PM daily',
  },
  branches: [
    {
      id: 'branch-1',
      name: 'Main Academy & RTO Simulator Hub',
      address: 'Plot 42, Sector 18, Road Safety Avenue',
      city: 'Delhi NCR',
      pincode: '110001',
      isMainBranch: true,
      phone: '+91 98765 43210',
      googleMapsUrl: 'https://maps.google.com',
    },
    {
      id: 'branch-2',
      name: 'South Bengaluru Training Center',
      address: '24th Main Road, HSR Layout Sector 2',
      city: 'Bengaluru',
      pincode: '560102',
      isMainBranch: false,
      phone: '+91 98765 43211',
      googleMapsUrl: 'https://maps.google.com',
    },
    {
      id: 'branch-3',
      name: 'Western Mumbai Practical Center',
      address: 'Link Road, Andheri West (Opposite Metro Pillar 140)',
      city: 'Mumbai',
      pincode: '400053',
      isMainBranch: false,
      phone: '+91 98765 43212',
      googleMapsUrl: 'https://maps.google.com',
    },
  ],
  socialLinks: [
    { platform: 'youtube', url: 'https://youtube.com/@drivecraftacademy', label: 'Driving Tips & Track Tutorials' },
    { platform: 'instagram', url: 'https://instagram.com/drivecraftacademy', label: 'Student Milestones & Tips' },
    { platform: 'facebook', url: 'https://facebook.com/drivecraftacademy', label: 'Community & Road Safety' },
    { platform: 'linkedin', url: 'https://linkedin.com/company/drivecraft-academy', label: 'Corporate Fleet Training' },
  ],
  trustStats: [
    { label: 'Learners Trained', value: '14,800+', subtext: 'Confidently driving on Indian roads' },
    { label: 'First-Attempt RTO Pass', value: '98.4%', subtext: 'Rigorous automated track drills' },
    { label: 'Certified Safety Instructors', value: '35+', subtext: 'Background verified & patient' },
    { label: 'Dual-Control Cars', value: '100%', subtext: 'Modern hatchbacks, sedans & SUVs' },
  ],
  serviceCities: [
    'Delhi NCR',
    'Bengaluru',
    'Mumbai',
    'Pune',
    'Hyderabad',
    'Chennai',
  ],
};
