import { SiteConfig } from '../types';

export const defaultSiteConfig: SiteConfig = {
  brandName: 'DriveCraft Motor Academy',
  tagline: 'Master Every Mile with Confidence & Safety',
  shortDescription: "India's premier certified driving academy providing 100% dual-control safety cars, patient certified instructors, automated RTO test-track preparation, and personalized doorstep lessons.",
  phoneDisplay: '+91 98765 43210',
  phoneDial: '+919876543210',
  whatsappNumber: '919876543210',
  whatsappDefaultMessage: 'Hello DriveCraft Academy! I would like to enquire about your driving courses and book a trial lesson.',
  email: 'admissions@drivecraft.in',
  emergencyHelpline: '1800-200-SAFE',
  foundedYear: '2016',
  operatingHours: {
    weekdays: '6:00 AM – 8:00 PM (Lessons every hour)',
    weekends: '6:30 AM – 7:30 PM (Special weekend batches)',
    note: 'Office support available 8:00 AM – 9:00 PM daily',
  },
  branches: [
    {
      id: 'branch-1',
      name: 'Main Academy & RTO Simulator Hub',
      address: 'Plot 42, Sector 18, Road Safety Avenue',
      city: 'Delhi NCR',
      pincode: '110001',
      isMainBranch: true,
      phone: '+91 98765 43210',
      googleMapsUrl: 'https://maps.google.com',
    },
    {
      id: 'branch-2',
      name: 'South Bengaluru Training Center',
      address: '24th Main Road, HSR Layout Sector 2',
      city: 'Bengaluru',
      pincode: '560102',
      isMainBranch: false,
      phone: '+91 98765 43211',
      googleMapsUrl: 'https://maps.google.com',
    },
    {
      id: 'branch-3',
      name: 'Western Mumbai Practical Center',
      address: 'Link Road, Andheri West (Opposite Metro Pillar 140)',
      city: 'Mumbai',
      pincode: '400053',
      isMainBranch: false,
      phone: '+91 98765 43212',
      googleMapsUrl: 'https://maps.google.com',
    },
  ],
  socialLinks: [
    { platform: 'youtube', url: 'https://youtube.com/@drivecraftacademy', label: 'Driving Tips & Track Tutorials' },
    { platform: 'instagram', url: 'https://instagram.com/drivecraftacademy', label: 'Student Milestones & Tips' },
    { platform: 'facebook', url: 'https://facebook.com/drivecraftacademy', label: 'Community & Road Safety' },
    { platform: 'linkedin', url: 'https://linkedin.com/company/drivecraft-academy', label: 'Corporate Fleet Training' },
  ],
  trustStats: [
    { label: 'Learners Trained', value: '14,800+', subtext: 'Confidently driving on Indian roads' },
    { label: 'First-Attempt RTO Pass', value: '98.4%', subtext: 'Rigorous automated track drills' },
    { label: 'Certified Safety Instructors', value: '35+', subtext: 'Background verified & patient' },
    { label: 'Dual-Control Cars', value: '100%', subtext: 'Modern hatchbacks, sedans & SUVs' },
  ],
  serviceCities: [
    'Delhi NCR',
    'Bengaluru',
    'Mumbai',
    'Pune',
    'Hyderabad',
    'Chennai',
  ],
};
