import { SiteConfig } from '../types';

export const defaultSiteConfig: SiteConfig = {
  brandName: 'DriveCraft Motor Academy',
  tagline: 'Master Every Mile with Confidence & Safety',
  shortDescription: "India's premier certified driving academy providing 100% dual-control safety cars, patient certified instructors, automated RTO test-track preparation, and personalized doorstep lessons.",
  phoneDisplay: '+91 98765 43210',
  phoneDial: '+919876543210',
  whatsappNumber: '919876543210',
  whatsappDefaultMessage: 'Hello DriveCraft Academy! I would like to enquire about your driving courses and book a trial lesson.',
  email: 'admissions@drivecraft.in',
  emergencyHelpline: '1800-200-SAFE',
  foundedYear: '2016',
  hero: {
    badgeText: '100% Dual-Control Safety Fleet • Doorstep Pickup',
    headlineMain: 'Master Every Mile with ',
    headlineHighlight: 'Confidence',
    headlineEnd: ' & Total Safety.',
    subtitle: 'Learn driving in modern dual-control cars with patient certified mentors, replica automated RTO track training, and zero hidden fees.',
    bookingButtonText: 'Book a Driving Lesson',
    whatsappButtonText: 'WhatsApp Us',
    heroImageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=800&q=80',
    trustChecks: ['98.4% First-Attempt RTO Pass', 'Female & Male Mentors', 'Manual & Auto'],
  },
  coreValues: [
    {
      id: 'val-1',
      title: '100% Dual-Control Safety Fleet',
      description: 'Every training vehicle is equipped with secondary dual pedals. Your instructor stops the vehicle instantly if any hazard arises.',
      icon: 'ShieldCheck',
    },
    {
      id: 'val-2',
      title: 'Automated RTO Track Readiness',
      description: 'Drills on replica Figure-8, H-box parking, and slope hill-hold tracks ensure high first-attempt pass rates on camera-monitored exams.',
      icon: 'Award',
    },
    {
      id: 'val-3',
      title: 'Doorstep Pickup & Calm Coaching',
      description: 'Daily 1-hour slots scheduled directly from your home or office with background-verified, patient male & female mentors.',
      icon: 'Compass',
    },
  ],
  teamMembers: [
    {
      id: 'inst-1',
      name: 'Rajesh Verma',
      role: 'Chief Safety Instructor & RTO Specialist',
      image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
      social: { twitter: '#', linkedin: '#' },
    },
    {
      id: 'inst-2',
      name: 'Pooja Sharma',
      role: 'Senior Instructor & Women-Priority Coach',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
      social: { twitter: '#', linkedin: '#', instagram: '#' },
    },
    {
      id: 'inst-3',
      name: 'Anand Sundaram',
      role: 'Technical Fleet Lead & Precision Maneuver Mentor',
      image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      social: { linkedin: '#' },
    },
    {
      id: 'inst-4',
      name: 'Simran Kaur',
      role: 'City Traffic & Commute Route Specialist',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
      social: { twitter: '#', linkedin: '#' },
    },
    {
      id: 'inst-5',
      name: 'Vikramaditya Shinde',
      role: 'Defensive Driving & Expressway Master',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      social: { linkedin: '#' },
    },
    {
      id: 'inst-6',
      name: 'Meenakshi Iyer',
      role: 'Refresher Program & Senior Driver Coach',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
      social: { twitter: '#', linkedin: '#' },
    },
    {
      id: 'inst-7',
      name: 'Kabir Malhotra',
      role: 'Automatic & EV Dual-Control Specialist',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
      social: { linkedin: '#' },
    },
    {
      id: 'inst-8',
      name: 'Sunita Patil',
      role: 'Night Driving & Parallel Parking Coach',
      image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=600&q=80',
      social: { instagram: '#' },
    },
    {
      id: 'inst-9',
      name: 'Arjun Nambiar',
      role: 'RTO Test Simulator & Hill-Hold Expert',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
      social: { linkedin: '#' },
    },
  ],
  operatingHours: {
    weekdays: '6:00 AM – 8:00 PM (Lessons every hour)',
    weekends: '6:30 AM – 7:30 PM (Special weekend batches)',
    note: 'Office support available 8:00 AM – 9:00 PM daily',
  },
  branches: [
    {
      id: 'branch-1',
      name: 'Main Academy & RTO Simulator Hub',
      address: 'Plot 42, Sector 18, Road Safety Avenue',
      city: 'Delhi NCR',
      pincode: '110001',
      isMainBranch: true,
      phone: '+91 98765 43210',
      googleMapsUrl: 'https://maps.google.com',
    },
    {
      id: 'branch-2',
      name: 'South Bengaluru Training Center',
      address: '24th Main Road, HSR Layout Sector 2',
      city: 'Bengaluru',
      pincode: '560102',
      isMainBranch: false,
      phone: '+91 98765 43211',
      googleMapsUrl: 'https://maps.google.com',
    },
    {
      id: 'branch-3',
      name: 'Western Mumbai Practical Center',
      address: 'Link Road, Andheri West (Opposite Metro Pillar 140)',
      city: 'Mumbai',
      pincode: '400053',
      isMainBranch: false,
      phone: '+91 98765 43212',
      googleMapsUrl: 'https://maps.google.com',
    },
  ],
  socialLinks: [
    { platform: 'youtube', url: 'https://youtube.com/@drivecraftacademy', label: 'Driving Tips & Track Tutorials' },
    { platform: 'instagram', url: 'https://instagram.com/drivecraftacademy', label: 'Student Milestones & Tips' },
    { platform: 'facebook', url: 'https://facebook.com/drivecraftacademy', label: 'Community & Road Safety' },
    { platform: 'linkedin', url: 'https://linkedin.com/company/drivecraft-academy', label: 'Corporate Fleet Training' },
  ],
  trustStats: [
    { label: 'Learners Trained', value: '14,800+', subtext: 'Confidently driving on Indian roads' },
    { label: 'First-Attempt RTO Pass', value: '98.4%', subtext: 'Rigorous automated track drills' },
    { label: 'Certified Safety Instructors', value: '35+', subtext: 'Background verified & patient' },
    { label: 'Dual-Control Cars', value: '100%', subtext: 'Modern hatchbacks, sedans & SUVs' },
  ],
  serviceCities: [
    'Delhi NCR',
    'Bengaluru',
    'Mumbai',
    'Pune',
    'Hyderabad',
    'Chennai',
  ],
};
