import { Testimonial } from '../types';

export const defaultTestimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Ananya Deshmukh',
    city: 'Pune',
    age: 24,
    courseTitle: 'Beginner Driving Mastery',
    rating: 5,
    date: 'February 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    story: 'I had extreme anxiety after trying to learn from my brother. Signing up with DriveCraft was the best decision. Pooja Ma’am was unimaginably patient. Passed my automated RTO "8" and "H" test on the very first try with zero sensor errors!',
    vehicleLearned: 'Hyundai Grand i10 (Manual)',
    instructorName: 'Pooja Sharma',
    firstTimePass: true,
    tag: 'Nervous Driver',
  },
  {
    id: 'test-2',
    name: 'Karthik Ramanathan',
    city: 'Bengaluru',
    age: 31,
    courseTitle: 'Automatic Transmission Specialist',
    rating: 5,
    date: 'January 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    story: 'Working in Whitefield, I had to commute daily in heavy Bengaluru traffic. Anand Sir focused heavily on creep speed in bumper-to-bumper traffic and tight basement parking. Now I drive my Honda City CVT to work every single day without any stress.',
    vehicleLearned: 'Maruti Baleno (Automatic CVT)',
    instructorName: 'Anand Sundaram',
    firstTimePass: true,
    tag: 'Working Professional',
  },
  {
    id: 'test-3',
    name: 'Suresh Chandra Mehta',
    city: 'Delhi NCR',
    age: 58,
    courseTitle: 'Refresher & Confidence Booster',
    rating: 5,
    date: 'December 2023',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    story: 'I held a driving licence for 15 years but never touched a car after moving to Delhi. Rajesh Sir was extremely respectful and methodically guided me through Noida-Greater Noida expressway merging and complex roundabout rules. Remarkable teaching method.',
    vehicleLearned: 'Maruti Dzire (Manual)',
    instructorName: 'Rajesh Verma',
    firstTimePass: true,
    tag: 'Senior Citizen',
  },
  {
    id: 'test-4',
    name: 'Tanya Sengupta',
    city: 'Mumbai',
    age: 22,
    courseTitle: 'Women-Priority Driving Coaching',
    rating: 5,
    date: 'March 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    story: 'Doorstep pickup in Andheri was super punctual. The dual-control brake gave me total peace of mind. Pooja Ma’am helped me conquer tight mall parking and Western Express Highway flyovers with ease. Truly empowering experience!',
    vehicleLearned: 'Tata Altroz (Manual)',
    instructorName: 'Pooja Sharma',
    firstTimePass: true,
    tag: 'First-time Driver',
  },
  {
    id: 'test-5',
    name: 'Rohan Mehra',
    city: 'Delhi NCR',
    age: 28,
    courseTitle: 'RTO Test-Track Readiness',
    rating: 5,
    date: 'November 2023',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    story: 'I had previously failed at the automated test track in Mayur Vihar because my rear wheel clipped the yellow line on the H-box. Rajesh Sir taught me the exact mirror markers. Cleared with a perfect 100/100 score in 4 minutes flat!',
    vehicleLearned: 'Maruti Swift (Manual)',
    instructorName: 'Rajesh Verma',
    firstTimePass: true,
    tag: 'First-time Driver',
  },
  {
    id: 'test-6',
    name: 'Deepa & Vikram Nair',
    city: 'Bengaluru',
    age: 36,
    courseTitle: 'Highway & Defensive Driving',
    rating: 5,
    date: 'January 2024',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    story: 'We wanted to drive from Bengaluru to Coorg for our vacation but were hesitant about ghat roads and highway overtaking. Vikramaditya Shinde gave us a stellar 3-hour expressway session with downhill engine braking techniques. Smooth trip with zero panic!',
    vehicleLearned: 'Hyundai Creta (Automatic)',
    instructorName: 'Vikramaditya Shinde',
    firstTimePass: true,
    tag: 'Highway Commuter',
  },
];
